### ISSUE TITLE
 is not of type 'object'

### ISSUE THREAD

**Issue by gabays** [HTR-United/HTRUC#14]
Hello!

Currently trying to push new data:
https://github.com/FoNDUE-HTR/FONDUE-FR-MSS-18

I have an error ([link](https://github.com/FoNDUE-HTR/FONDUE-FR-MSS-18/actions/runs/6920957819/job/18826018826))
```
☒ File `htr-united.yml` testing failed
  Path `hands`: 'precision' is a required property
  Path `license`: [ordereddict([('name', 'CC-BY 4.0'), ('url', 'https://creativecommons.org/licenses/by/4.0/')])] is not of type 'object'
```
My `htr-united-yml` is here:
https://github.com/FoNDUE-HTR/FONDUE-FR-MSS-18/blob/main/htr-united.yml

Any idea what the trouble is?

**Comment by PonteIneptique** [comment]
It might be a mistake in the generator rather than in HTRUC.

**Comment by gabays** [comment]
Thx.
Any idea how to solve that?

**Comment by gabays** [comment]
I've seen the Pr. Thx
